// Generated by CoffeeScript 1.7.1
exports.index = function(req, res) {
  console.log("connect.sid: ", req.cookies["connect.sid"]);
  return res.render('index');
};

exports.admin = function(req, res) {
  if (req.isAuthenticated()) {
    return res.render('admin');
  } else {
    return res.redirect('/');
  }
};

exports.partials = function(req, res) {
  var name;
  name = req.params.name;
  return res.render('partials/' + name);
};

exports.partialsAdmin = function(req, res) {
  var name;
  name = req.params.name;
  return res.render('partials/admin/' + name);
};

exports.templates = function(req, res) {
  var name;
  name = req.params.name;
  return res.render('partials/templates/' + name);
};
